model: ollama/qwen3-30b-aider:latest
edit-format: whole
yes-always: true
auto-commits: true
auto-test: false
suggest-shell-commands: true
map-tokens: 768
max-chat-history-tokens: 1536
cache-prompts: true
attribute-author: false
attribute-committer: false
dark-mode: true
model-metadata-file: .aider.model.metadata.json
