model: ollama/llama3.1:32k
edit-format: whole
yes-always: true
auto-commits: true
auto-test: false
suggest-shell-commands: true
map-tokens: 2048
max-chat-history-tokens: 4096
cache-prompts: true
attribute-author: false
attribute-committer: false
dark-mode: true
model-metadata-file: .aider.model.metadata.json
