model: ollama/qwen2.5-coder:32k
edit-format: whole
yes-always: true
auto-commits: true
auto-test: false
suggest-shell-commands: true
map-tokens: 4096
max-chat-history-tokens: 8192
cache-prompts: true
attribute-author: false
attribute-committer: false
dark-mode: true
model-metadata-file: .aider.model.metadata.json
